name: Docs
on: [push, pull_request, workflow_dispatch]

permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Connect path to the modules
        run: |
          echo "PYTHONPATH=/home/runner/work/scope-rl/scope-rl" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          pip install Sphinx pydata-sphinx-theme numpydoc sphinx_design sphinx-gallery sphinx-tabs sphinx-copybutton sphinxemoji sphinxcontrib-bibtex
      - name: Install scope-rl from pip
        run: |
          git clone https://github.com/hakuhodo-technologies/scope-rl
          cd scope-rl
      - name: Sphinx build
        run: |
          sphinx-build -b html docs docs/_build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' }}
        with:
          publish_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/
          force_orphan: true
